using System.Collections.Generic;

namespace PascalCompiler
{
    public class Symbol
    {
        public enum SymbolEnum
        {
            Star,
            Slash,
            Equals,
            NotEquals,
            Comma,
            Semicolon,
            Colon,
            Point,
            Arrow,
            LeftRoundBracket,
            RightRoundBracket,
            LeftSquareBracket,
            RightSquareBracket,
            LeftCurlyBracket,
            RightCurlyBracket,
            Less,
            Greater,
            LessEquals,
            GreaterEquals,
            Plus,
            Minus,
            LeftComment,
            RightComment,
            Assign,
            TwoPoints,
            Identifier,
            FLoatConstant,
            IntConstant,
            CharConstant,

            // Reserved words
            AndSy,
            ArraySy,
            AsmSy,
            BeginSy,
            BreakSy,
            CaseSy,
            ConstSy,
            ConstructorSy,
            ContinueSy,
            DestructorSy,
            DivSy,
            DoSy,
            DowntoSy,
            ElseSy,
            EndSy,
            FalseSy,
            FileSy,
            ForSy,
            FunctionSy,
            GotoSy,
            IfSy,
            ImplementationSy,
            InSy,
            InlineSy,
            InterfaceSy,
            LabelSy,
            ModSy,
            NilSy,
            NotSy,
            ObjectSy,
            OfSy,
            OnSy,
            OperatorSy,
            OrSy,
            PackedSy,
            ProcedureSy,
            ProgramSy,
            RecordSy,
            RepeatSy,
            SetSy,
            ShlSy,
            ShrSy,
            ThenSy,
            ToSy,
            TrueSy,
            TypeSy,
            UnitSy,
            UntilSy,
            UsesSy,
            VarSy,
            WhileSy,
            WithSy,
            XorSy,

            BooleanSy,
            ByteSy,
            CharSy,
            IntegerSy,
            RealSy,
            StringSy,
        }

        public static Dictionary<string, SymbolEnum> keywordMapping = new Dictionary<string, SymbolEnum>()
        {
            { "array", SymbolEnum.ArraySy },
            { "begin", SymbolEnum.BeginSy },
            { "do", SymbolEnum.DoSy },
            { "else", SymbolEnum.ElseSy },
            { "end", SymbolEnum.EndSy },
            { "for", SymbolEnum.ForSy },
            { "if", SymbolEnum.IfSy },
            { "in", SymbolEnum.InSy },
            { "of", SymbolEnum.OfSy },
            { "procedure", SymbolEnum.ProcedureSy },
            { "program", SymbolEnum.ProgramSy },
            { "type", SymbolEnum.TypeSy },
            { "var", SymbolEnum.VarSy },
            { "while", SymbolEnum.WhileSy },

            { "boolean", SymbolEnum.BooleanSy },
            { "byte", SymbolEnum.ByteSy },
            { "integer", SymbolEnum.IntegerSy },
            { "real", SymbolEnum.RealSy },
        };
    }
}
